POST http://localhost:3003/signup
content-type: application/json

{
    "name": "Test name",
    "email": "email@email.com",
    "password": "12345",    
    "zipCode": "99999991"    
}

### Login

POST http://localhost:3003/login
content-type: application/json

{    
    "email": "email@email.com",
    "password": "12345"    
}
