POST http://localhost:3003/register
content-type: application/json

{
    "name": "Test name",
    "email": "email@email.com",
    "age": 9,
    "address": {
       "country": "BR",
       "zipCode": "99999991"
    }
}

###

GET http://localhost:3003/getAllAccounts
content-type: application/json

{}