GET http://localhost:3003/users
Authorization: 66708c0d-5cea-4fde-a3df-23232acadb75
content-type: application/json

{}

### Get by id

GET http://localhost:3003/users/bd10c4e7-6385-41a6-a9d1-90c0ee80db0d
Authorization: d15ce219-d512-4e77-b61d-0a10a5ad694a
content-type: application/json

{}